browser=Edge
url=https://automationexercise.com/
loginUrl=https://automationexercise.com/login
productsUrl=https://automationexercise.com/products
username=neerajsingh41150@gmail.com
password=Neeraj@123
